name: derulo
version: 0.0.4

category: JSON
description: Derulo parses and renders JSON simply.
extra-source-files:
  - CHANGELOG.markdown
  - README.markdown
github: tfausak/derulo
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and render JSON simply.

dependencies:
  - base >=4.8.2 && <4.11
ghc-options:
  - -Wall

library:
  source-dirs: library

executables:
  derulo:
    dependencies:
      - derulo
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: executables

tests:
  test:
    dependencies:
      - doctest >=0.11.0 && <0.14
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
