name: derulo
version: 1.0.4

category: JSON
description: Derulo parses and renders JSON simply.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/derulo
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and render JSON simply.

dependencies:
  base: '>= 4.9.0 && < 4.13'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies:
    derulo: -any
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables

tests:
  test:
    dependencies:
      doctest: '>= 0.11.0 && < 0.17'
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
